import * as ecp from "../services/ecpService.js";
const actor = req => req.user?.id || req.user?._id;
const ok = (res, data) => res.json(data?.success === undefined ? { success: true, data } : data);
const fail = (res, err) => res.status(err.status || 500).json({ success:false, error: err.message || "Enterprise control plane request failed", code: err.code || "ECP_ERROR" });
const wrap = fn => async (req,res) => { try { return ok(res, await fn(req)); } catch (e) { return fail(res,e); } };
export const getExecutiveDashboard = wrap(() => ecp.getExecutiveDashboard());
export const getSystemHealth = wrap(() => ecp.getSystemHealth());
export const checkServiceHealth = wrap(req => ecp.checkServiceHealth(req.params.serviceId || req.params.id));
export const getBusinessHealth = wrap(() => ecp.getBusinessHealth());
export const getIncidents = wrap(req => ecp.getIncidents(req.query));
export const getIncident = wrap(req => ecp.getIncident(req.params.id));
export const createIncident = wrap(req => ecp.createIncidentRecord(req.body, actor(req), req));
export const updateIncident = wrap(req => ecp.updateIncidentRecord(req.params.id, req.body, actor(req), req));
export const deleteIncident = wrap(req => ecp.deleteIncidentRecord(req.params.id, actor(req), req));
export const resolveIncident = wrap(req => ecp.updateIncidentRecord(req.params.id, { status:"resolved" }, actor(req), req));
export const getAlerts = wrap(req => ecp.getAlerts(req.query));
export const createAlert = wrap(req => ecp.createAlertRecord(req.body, actor(req), req));
export const acknowledgeAlert = wrap(req => ecp.acknowledgeAlert(req.params.id, actor(req), req));
export const resolveAlert = wrap(req => ecp.resolveAlert(req.params.id, actor(req), req));
export const getSelfHealingActions = wrap(() => ecp.getSelfHealingActions());
export const executeSelfHealing = wrap(req => ecp.executeSelfHealing(req.body, actor(req), req));
export const executeSelfHealingAction = executeSelfHealing;
export const getSelfHealingRules = wrap(() => ecp.getSelfHealingRules());
export const getRootCauseAnalysis = wrap(req => ecp.getRootCauseAnalysis(req.params.incidentId || req.params.id));
export const getPerformanceMetrics = wrap(() => ecp.getPerformanceMetrics());
export const getSecurityStatus = wrap(() => ecp.getSecurityStatus());
export const getCapacityPlanning = wrap(() => ecp.getCapacityPlanning());
export const getComplianceStatus = wrap(() => ecp.getComplianceStatus());
export const getAuditLogs = wrap(req => ecp.getAuditLogs(req.query));
export const askOperationsQuestion = wrap(req => ecp.askOperationsQuestion(req.body?.question));
export const getDeployments = wrap(() => ecp.getDeployments());
export const getDisasterRecovery = wrap(() => ecp.getDisasterRecovery());
