import crypto from 'crypto';
import db from '../db/index.js';
import partnerPlatformService from '../partnerPlatform/services/partnerPlatformService.js';
import { AppError } from '../utils/AppError.js';
import { logAuditEvent } from '../services/auditService.js';

const ADMIN_ROLES = new Set(['admin', 'superadmin']);
const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const text = (v, max = 500) => String(v ?? '').trim().slice(0, max);
const id = (v, name = 'id') => { const value = text(v, 80); if (!UUID_RE.test(value)) throw new AppError(`${name} must be a valid UUID`, 400); return value; };
const admin = (req) => { if (!ADMIN_ROLES.has(req.user?.effectiveRole || req.user?.role)) throw new AppError('Administrator access required', 403); };
const audit = (req, action, target, details = {}) => logAuditEvent({ action, actor: req.user.id, actorRole: req.user.effectiveRole || req.user.role, actorName: req.user.name, actorEmail: req.user.email, target, targetModel: 'Integration', details, ipAddress: req.ip, userAgent: req.get('user-agent'), requestId: req.id });
const publicCredential = (row) => { if (!row) return row; const { api_secret_hash, oauth_client_secret_hash, api_secret_plaintext, oauth_client_secret_plaintext, ...safe } = row; return safe; };
const validateUrl = (value) => { try { const u = new URL(value); if (u.protocol !== 'https:') throw new AppError('Webhook URL must use HTTPS', 400); if (u.username || u.password) throw new AppError('Webhook URL must not contain credentials', 400); const host = u.hostname.toLowerCase(); if (['localhost', '127.0.0.1', '::1'].includes(host) || host.endsWith('.local')) throw new AppError('Webhook URL host is not allowed', 400); return u.toString(); } catch (e) { if (e instanceof AppError) throw e; throw new AppError('Invalid webhook URL', 400); } };

export async function getAPIs(req, res) { admin(req); return res.json({ success: true, data: await partnerPlatformService.getAvailableEndpoints() }); }
export async function getAPIDetails(req, res) { admin(req); const endpoint = await db.findById('api_endpoints', id(req.params.apiId, 'apiId')); if (!endpoint) throw new AppError('API endpoint not found', 404); return res.json({ success: true, data: endpoint }); }
export async function getPartners(req, res) { admin(req); const data = await partnerPlatformService.searchPartners({ partnerType: text(req.query.partnerType, 50) || undefined, country: text(req.query.country, 50) || undefined, verificationStatus: text(req.query.verificationStatus, 30) || undefined, limit: Math.min(Number(req.query.limit) || 50, 100) }); return res.json({ success: true, data }); }
export async function getPartner(req, res) { admin(req); return res.json({ success: true, data: await partnerPlatformService.getPartner(id(req.params.id)) }); }
export async function createPartner(req, res) { admin(req); const body = req.body || {}; for (const key of ['organizationName','partnerType','primaryContactEmail','country']) if (!text(body[key], 200)) throw new AppError(`${key} is required`, 400); const data = await partnerPlatformService.registerPartner(body); await audit(req, 'integration_partner_created', data.id); return res.status(201).json({ success: true, data }); }
export async function updatePartner(req, res) { admin(req); const partnerId = id(req.params.id); const allowed = ['organizationName','partnerType','primaryContactName','primaryContactEmail','primaryContactPhone','technicalContactName','technicalContactEmail','country','city','address','website','registrationNumber','taxId','status','verificationStatus']; const current = await db.findById('partner_organizations', partnerId); if (!current) throw new AppError('Partner not found', 404); const updates = {}; for (const key of allowed) if (req.body?.[key] !== undefined) updates[key] = req.body[key]; if (!Object.keys(updates).length) throw new AppError('No permitted fields supplied', 400); const data = await db.update('partner_organizations', partnerId, { ...updates, updatedAt: new Date() }); await audit(req, 'integration_partner_updated', partnerId, { fields: Object.keys(updates) }); return res.json({ success: true, data }); }
export async function deletePartner(req, res) { admin(req); const partnerId = id(req.params.id); const current = await db.findById('partner_organizations', partnerId); if (!current) throw new AppError('Partner not found', 404); const data = await db.update('partner_organizations', partnerId, { status: 'suspended', updatedAt: new Date() }); await audit(req, 'integration_partner_suspended', partnerId); return res.json({ success: true, data }); }

export async function getAPIKeys(req, res) { admin(req); const applicationId = req.query.applicationId ? id(req.query.applicationId, 'applicationId') : null; const rows = await db.find('api_credentials', applicationId ? { application_id: applicationId } : {}); return res.json({ success: true, data: rows.map(publicCredential) }); }
export async function createAPIKey(req, res) { admin(req); const applicationId = id(req.body?.applicationId, 'applicationId'); const environment = ['sandbox','production'].includes(req.body?.environment) ? req.body.environment : 'sandbox'; const credential = await partnerPlatformService.generateCredentials(applicationId, environment); await audit(req, 'integration_api_key_created', credential.id, { applicationId, environment }); return res.status(201).json({ success: true, data: publicCredential(credential), secret: credential.api_secret_plaintext }); }
export async function revokeAPIKey(req, res) { admin(req); const credentialId = id(req.params.id); const current = await db.findById('api_credentials', credentialId); if (!current) throw new AppError('Credential not found', 404); await partnerPlatformService.revokeCredentials(credentialId); await audit(req, 'integration_api_credential_revoked', credentialId); return res.json({ success: true }); }

export async function getWebhooks(req, res) { admin(req); const rows = await db.find('webhook_configs', req.query.applicationId ? { application_id: id(req.query.applicationId, 'applicationId') } : {}); return res.json({ success: true, data: rows.map(({ secret_key, ...safe }) => safe) }); }
export async function getWebhook(req, res) { admin(req); const webhook = await db.findById('webhook_configs', id(req.params.id)); if (!webhook) throw new AppError('Webhook not found', 404); const { secret_key, ...safe } = webhook; return res.json({ success: true, data: safe }); }
export async function createWebhook(req, res) { admin(req); const applicationId = id(req.body?.applicationId, 'applicationId'); const webhookUrl = validateUrl(req.body?.webhookUrl); if (!Array.isArray(req.body?.subscribedEvents) || req.body.subscribedEvents.length === 0) throw new AppError('At least one subscribed event is required', 400); const webhook = await partnerPlatformService.createWebhook(applicationId, { webhookUrl, webhookName: text(req.body.webhookName, 200), subscribedEvents: req.body.subscribedEvents.slice(0, 50).map(e => text(e, 80)), }); await audit(req, 'integration_webhook_created', webhook.id, { applicationId }); const { secret_key_plaintext, secret_key, ...safe } = webhook; return res.status(201).json({ success: true, data: safe, secret: secret_key_plaintext }); }
export async function updateWebhook(req, res) { admin(req); const webhookId = id(req.params.id); const current = await db.findById('webhook_configs', webhookId); if (!current) throw new AppError('Webhook not found', 404); const updates = {}; if (req.body?.webhookUrl !== undefined) updates.webhookUrl = validateUrl(req.body.webhookUrl); if (req.body?.webhookName !== undefined) updates.webhookName = text(req.body.webhookName, 200); if (req.body?.subscribedEvents !== undefined) { if (!Array.isArray(req.body.subscribedEvents)) throw new AppError('subscribedEvents must be an array', 400); updates.subscribedEvents = req.body.subscribedEvents.slice(0, 50).map(e => text(e, 80)); } if (req.body?.status !== undefined && ['active','paused','disabled'].includes(req.body.status)) updates.status = req.body.status; if (!Object.keys(updates).length) throw new AppError('No permitted fields supplied', 400); const data = await partnerPlatformService.updateWebhook(webhookId, updates); const { secret_key, ...safe } = data; await audit(req, 'integration_webhook_updated', webhookId, { fields: Object.keys(updates) }); return res.json({ success: true, data: safe }); }
export async function deleteWebhook(req, res) { admin(req); const webhookId = id(req.params.id); const current = await db.findById('webhook_configs', webhookId); if (!current) throw new AppError('Webhook not found', 404); await partnerPlatformService.deleteWebhook(webhookId); await audit(req, 'integration_webhook_paused', webhookId); return res.json({ success: true }); }
export async function testWebhook(req, res) { admin(req); const webhookId = id(req.params.id); const webhook = await db.findById('webhook_configs', webhookId); if (!webhook) throw new AppError('Webhook not found', 404); const eventType = text(req.body?.eventType, 80) || 'integration.test'; const delivery = await partnerPlatformService.deliverWebhook(webhook, eventType, { id: crypto.randomUUID(), test: true }); await audit(req, 'integration_webhook_tested', webhookId, { eventType }); return res.json({ success: true, data: delivery }); }
export async function getWebhookLogs(req, res) { admin(req); const webhookId = id(req.params.webhookId, 'webhookId'); const rows = await db.find('webhook_deliveries', { webhook_id: webhookId }, { sort: { created_at: -1 }, limit: Math.min(Number(req.query.limit) || 50, 200) }); return res.json({ success: true, data: rows }); }

export async function getPlugins(req, res) { admin(req); return res.json({ success: true, data: await db.find('integration_plugins', { status: { $ne: 'deleted' } }) }); }
export async function getPlugin(req, res) { admin(req); const data = await db.findById('integration_plugins', id(req.params.id)); if (!data) throw new AppError('Plugin not found', 404); return res.json({ success: true, data }); }
export async function createPlugin(req, res) { admin(req); const name=text(req.body?.name,200), code=text(req.body?.code,100), version=text(req.body?.version,30); if (!name || !code || !version) throw new AppError('name, code and version are required',400); const data=await db.create('integration_plugins',{name,code,version,description:text(req.body.description,500),config:req.body.config&&typeof req.body.config==='object'?req.body.config:{},status:'active'}); await audit(req,'integration_plugin_created',data.id); return res.status(201).json({success:true,data}); }
export async function updatePlugin(req, res) { admin(req); const pluginId=id(req.params.id); const data=await db.findById('integration_plugins',pluginId); if(!data)throw new AppError('Plugin not found',404); const updates={}; for(const key of ['name','description','version','status'])if(req.body?.[key]!==undefined)updates[key]=text(req.body[key],200); if(req.body?.config!==undefined&&req.body.config&&typeof req.body.config==='object'&&!Array.isArray(req.body.config))updates.config=req.body.config; if(!Object.keys(updates).length)throw new AppError('No permitted fields supplied',400); const row=await db.update('integration_plugins',pluginId,{...updates,updatedAt:new Date()}); await audit(req,'integration_plugin_updated',pluginId,{fields:Object.keys(updates)}); return res.json({success:true,data:row}); }
export async function deletePlugin(req, res) { admin(req); const pluginId=id(req.params.id); const data=await db.findById('integration_plugins',pluginId); if(!data)throw new AppError('Plugin not found',404); await db.update('integration_plugins',pluginId,{status:'disabled',updatedAt:new Date()}); await audit(req,'integration_plugin_disabled',pluginId); return res.json({success:true}); }
export async function getTemplates(req, res) { admin(req); return res.json({success:true,data:await db.find('integration_templates',{status:'active'})}); }
export async function getTemplate(req, res) { admin(req); const data=await db.findById('integration_templates',id(req.params.id)); if(!data)throw new AppError('Template not found',404); return res.json({success:true,data}); }
export async function getAPIAnalytics(req, res) { admin(req); const applicationId=req.query.applicationId?id(req.query.applicationId,'applicationId'):null; if(applicationId)return res.json({success:true,data:await partnerPlatformService.getApplicationAnalytics(applicationId)}); const logs=await db.find('api_usage_logs',{}, {sort:{created_at:-1},limit:1000}); const total=logs.length, successful=logs.filter(x=>Number(x.status_code)<400).length; return res.json({success:true,data:{totalRequests:total,successfulRequests:successful,failedRequests:total-successful,successRate:total?Math.round(successful/total*10000)/100:100,avgResponseTime:total?Math.round(logs.reduce((s,x)=>s+Number(x.response_time_ms||0),0)/total):0}}); }
export async function getSDKs(req, res) { admin(req); return res.json({success:true,data:await db.find('integration_sdks',{status:'active'})}); }
export async function getOAuthConfig(req, res) { admin(req); const clients=await db.find('oauth_clients',{status:'active'}); return res.json({success:true,data:clients.map(({client_secret_hash,...safe})=>safe)}); }
export async function createOAuthClient(req, res) { admin(req); const name=text(req.body?.name,200); if(!name)throw new AppError('name is required',400); const secret=crypto.randomBytes(32).toString('hex'); const hash=crypto.createHash('sha256').update(secret).digest('hex'); const clientId=`kayad_oauth_${crypto.randomBytes(10).toString('hex')}`; const data=await db.create('oauth_clients',{clientId,clientSecretHash:hash,name,redirectUris:Array.isArray(req.body?.redirectUris)?req.body.redirectUris.slice(0,10):[],scopes:Array.isArray(req.body?.scopes)?req.body.scopes.slice(0,30):[],status:'active'}); await audit(req,'integration_oauth_client_created',data.id); return res.status(201).json({success:true,data,clientSecret:secret}); }
export async function getEvents(req, res) { admin(req); return res.json({success:true,data:await db.find('integration_events',{}, {sort:{created_at:-1},limit:Math.min(Number(req.query.limit)||100,500)})}); }
export async function getGatewayStatus(req, res) { admin(req); const [endpoints, logs] = await Promise.all([db.find('api_endpoints',{is_active:true}),db.find('api_usage_logs',{}, {sort:{created_at:-1},limit:200})]); return res.json({success:true,data:{status:'operational',activeEndpoints:endpoints.length,recentRequests:logs.length}}); }
export async function getSandbox(req, res) { admin(req); return res.json({success:true,data:await db.find('sandbox_environments',{status:'active'})}); }
export async function getCertificationStatus(req, res) { admin(req); const rows=await db.find('integration_certifications',req.query.applicationId?{application_id:id(req.query.applicationId,'applicationId')}:{}); return res.json({success:true,data:rows}); }
export async function getIntegrationHelp(req, res) { admin(req); const q=text(req.body?.question,500).toLowerCase(); const guidance=q.includes('webhook')?'Use HTTPS webhook endpoints, subscribe only to required events, and verify the HMAC-SHA256 signature on every delivery.':q.includes('api key')?'Create environment-specific credentials, grant least-privilege permissions, rotate and revoke credentials when no longer required.':q.includes('oauth')?'Use registered redirect URIs and least-privilege scopes; never expose client secrets in browser code.':'Use the Integration Studio records and operational telemetry as the source of truth; do not treat client-side state as authoritative.'; return res.json({success:true,data:{answer:guidance}}); }
export async function getIntegrationDashboard(req, res) { admin(req); const [partners, apps, credentials, webhooks, deliveries, logs] = await Promise.all([db.find('partner_organizations',{status:'active'}),db.find('partner_applications',{}),db.find('api_credentials',{status:'active'}),db.find('webhook_configs',{status:'active'}),db.find('webhook_deliveries',{}, {sort:{created_at:-1},limit:500}),db.find('api_usage_logs',{}, {sort:{created_at:-1},limit:500})]); const failedDeliveries=deliveries.filter(d=>d.status==='failed').length; return res.json({success:true,data:{partners:partners.length,applications:apps.length,activeCredentials:credentials.length,activeWebhooks:webhooks.length,recentApiRequests:logs.length,recentWebhookDeliveries:deliveries.length,failedWebhookDeliveries:failedDeliveries,health:failedDeliveries>10?'degraded':'operational'}}); }
