import asyncHandler from '../middleware/asyncHandler.js';
import localizationService from '../services/localization.service.js';

export const getTranslations = asyncHandler(async (req, res) => res.json({ success: true, data: { locale: req.query.locale || 'en', namespace: req.query.namespace || 'common', translations: await localizationService.getTranslations(req.query.locale, req.query.namespace) } }));
export const getAllNamespaces = asyncHandler(async (req, res) => res.json({ success: true, data: { locale: req.query.locale || 'en', namespaces: await localizationService.getAllNamespaces(req.query.locale) } }));
export const getAllTranslations = asyncHandler(async (req, res) => res.json({ success: true, data: { locale: req.query.locale || 'en', translations: await localizationService.getAllTranslations(req.query.locale) } }));
export const searchTranslations = asyncHandler(async (req, res) => res.json({ success: true, data: await localizationService.search(req.query) }));
export const createTranslation = asyncHandler(async (req, res) => res.status(201).json({ success: true, data: await localizationService.upsertTranslation(req.body) }));
export const updateTranslation = asyncHandler(async (req, res) => res.json({ success: true, data: await localizationService.update(req.params.translationId, req.body) }));
export const deleteTranslation = asyncHandler(async (req, res) => { await localizationService.remove(req.params.translationId); res.json({ success: true, message: 'Translation deleted' }); });
export const importTranslations = asyncHandler(async (req, res) => { if (!Array.isArray(req.body.translations)) return res.status(400).json({ success: false, message: 'Translations must be an array' }); const results = await Promise.all(req.body.translations.map((item) => localizationService.upsertTranslation({ ...item, locale: req.body.locale, namespace: item.namespace || req.body.namespace || 'common' }))); res.json({ success: true, data: { locale: req.body.locale, imported: results.length } }); });
export const exportTranslations = asyncHandler(async (req, res) => res.json({ success: true, data: { locale: req.query.locale || 'en', namespace: req.query.namespace, translations: req.query.namespace ? await localizationService.getTranslations(req.query.locale, req.query.namespace) : await localizationService.getAllTranslations(req.query.locale), exportedAt: new Date().toISOString() } }));
export const getKeyInAllLocales = asyncHandler(async (req, res) => res.json({ success: true, data: { key: req.params.key, namespace: req.query.namespace || 'common', translations: await localizationService.getKeyInAllLocales(req.params.key, req.query.namespace) } }));
export const getTranslationStats = asyncHandler(async (_req, res) => res.json({ success: true, data: await localizationService.getStats() }));
