-- KAYAD Integration, Partner & Webhook domain
create table if not exists partner_organizations (id uuid primary key default gen_random_uuid(), organization_code varchar(50) unique not null, organization_name varchar(200) not null, partner_type varchar(30) not null, primary_contact_name varchar(100), primary_contact_email varchar(200) not null, primary_contact_phone varchar(30), technical_contact_name varchar(100), technical_contact_email varchar(200), country varchar(50) not null, city varchar(100), address text, website varchar(200), verification_status varchar(20) default 'pending', verified_at timestamptz, verified_by uuid, registration_number varchar(50), tax_id varchar(50), business_type varchar(50), status varchar(20) default 'active', created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists partner_applications (id uuid primary key default gen_random_uuid(), application_code varchar(50) unique not null, partner_id uuid references partner_organizations(id) on delete cascade, application_name varchar(200) not null, application_description text, application_website varchar(200), use_case text not null, expected_volume varchar(50), onboarding_step varchar(30) default 'register', data_processing_agreement_signed boolean default false, api_agreement_signed boolean default false, agreements_signed_at timestamptz, reviewed_by uuid, reviewed_at timestamptz, review_notes text, status varchar(20) default 'pending', created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists api_credentials (id uuid primary key default gen_random_uuid(), credential_code varchar(50) unique not null, application_id uuid references partner_applications(id) on delete cascade, api_key varchar(100) not null, api_secret_hash varchar(255) not null, oauth_client_id varchar(100), oauth_client_secret_hash varchar(255), credential_type varchar(20) not null, environment varchar(20) not null, permissions jsonb default '[]'::jsonb, status varchar(20) default 'active', last_used_at timestamptz, last_ip varchar(50), expires_at timestamptz, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists api_endpoints (id uuid primary key default gen_random_uuid(), endpoint_code varchar(50) unique not null, endpoint_name varchar(200) not null, endpoint_description text, api_version varchar(20) default 'v1', base_path varchar(100) not null, allowed_methods jsonb default '["GET"]'::jsonb, rate_limit_per_minute integer default 60, rate_limit_per_day integer default 10000, required_permissions jsonb default '[]'::jsonb, is_active boolean default true, is_public boolean default false, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists webhook_configs (id uuid primary key default gen_random_uuid(), config_code varchar(50) unique not null, application_id uuid references partner_applications(id) on delete cascade, webhook_url varchar(500) not null, webhook_name varchar(200), subscribed_events jsonb default '[]'::jsonb, filter_conditions jsonb default '{}'::jsonb, secret_key varchar(255) not null, signature_method varchar(20) default 'hmac_sha256', allowed_ips jsonb default '[]'::jsonb, status varchar(20) default 'active', delivery_attempts integer default 0, success_count integer default 0, failure_count integer default 0, last_delivery_at timestamptz, last_delivery_status varchar(20), created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists webhook_deliveries (id uuid primary key default gen_random_uuid(), delivery_code varchar(50) unique not null, webhook_id uuid references webhook_configs(id) on delete cascade, event_type varchar(50) not null, event_id uuid, event_data jsonb not null, request_payload jsonb not null, request_headers jsonb, request_timestamp timestamptz default now(), response_status integer, response_body text, response_time_ms integer, status varchar(20) default 'pending', retry_count integer default 0, next_retry_at timestamptz, created_at timestamptz default now(), delivered_at timestamptz);
create table if not exists api_usage_logs (id uuid primary key default gen_random_uuid(), request_id uuid not null, credential_id uuid references api_credentials(id), partner_id uuid references partner_organizations(id), application_id uuid references partner_applications(id), method varchar(10) not null, endpoint varchar(200) not null, api_version varchar(20), status_code integer, response_time_ms integer, request_ip varchar(50), request_user_agent text, request_size_bytes integer, response_size_bytes integer, created_at timestamptz default now());
create table if not exists partner_permissions (id uuid primary key default gen_random_uuid(), permission_code varchar(50) unique not null, permission_name varchar(200) not null, permission_description text, category varchar(50) not null, risk_level varchar(20) default 'low', requires_approval boolean default true, created_at timestamptz default now());
create table if not exists partner_documents (id uuid primary key default gen_random_uuid(), partner_id uuid references partner_organizations(id) on delete cascade, document_type varchar(50) not null, document_name varchar(200) not null, file_url varchar(500), file_name varchar(200), is_verified boolean default false, verified_at timestamptz, verified_by uuid, created_at timestamptz default now());
create table if not exists partner_tickets (id uuid primary key default gen_random_uuid(), ticket_code varchar(50) unique not null, partner_id uuid references partner_organizations(id), application_id uuid references partner_applications(id), contact_name varchar(100) not null, contact_email varchar(200) not null, ticket_type varchar(50) not null, subject varchar(300) not null, description text not null, priority varchar(10) default 'normal', status varchar(20) default 'open', assigned_to uuid, assigned_to_name varchar(100), resolution text, resolved_at timestamptz, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists partner_analytics (id uuid primary key default gen_random_uuid(), partner_id uuid references partner_organizations(id), application_id uuid references partner_applications(id), period_type varchar(20) not null, period_start timestamptz not null, period_end timestamptz not null, total_requests integer default 0, successful_requests integer default 0, failed_requests integer default 0, avg_response_time_ms integer default 0, endpoint_usage jsonb default '{}'::jsonb, rate_limit_hits integer default 0, webhooks_sent integer default 0, webhooks_failed integer default 0, calculated_at timestamptz default now(), unique(partner_id,application_id,period_type,period_start));
create table if not exists integration_plugins (id uuid primary key default gen_random_uuid(), name varchar(200) not null, code varchar(100) unique not null, description text, version varchar(30) not null, config jsonb default '{}'::jsonb, status varchar(20) default 'active', created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists integration_templates (id uuid primary key default gen_random_uuid(), name varchar(200) not null, code varchar(100) unique not null, description text, category varchar(50), configuration jsonb default '{}'::jsonb, status varchar(20) default 'active', created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists integration_sdks (id uuid primary key default gen_random_uuid(), language varchar(50) not null, version varchar(30) not null, package_name varchar(200), repository_url varchar(500), documentation_url varchar(500), status varchar(20) default 'active', created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists oauth_clients (id uuid primary key default gen_random_uuid(), client_id varchar(120) unique not null, client_secret_hash varchar(255) not null, name varchar(200) not null, redirect_uris jsonb default '[]'::jsonb, scopes jsonb default '[]'::jsonb, status varchar(20) default 'active', created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists integration_events (id uuid primary key default gen_random_uuid(), event_type varchar(100) not null, source varchar(100), payload jsonb not null, created_at timestamptz default now());
create table if not exists sandbox_environments (id uuid primary key default gen_random_uuid(), name varchar(100) not null, base_url varchar(300) not null, status varchar(20) default 'active', configuration jsonb default '{}'::jsonb, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists integration_certifications (id uuid primary key default gen_random_uuid(), application_id uuid references partner_applications(id) on delete cascade, status varchar(30) default 'pending', checks jsonb default '[]'::jsonb, certified_at timestamptz, certified_by uuid, created_at timestamptz default now(), updated_at timestamptz default now());
create index if not exists idx_partner_org_status on partner_organizations(status); create index if not exists idx_partner_apps_partner on partner_applications(partner_id); create index if not exists idx_credentials_app on api_credentials(application_id); create index if not exists idx_webhooks_app on webhook_configs(application_id); create index if not exists idx_deliveries_webhook on webhook_deliveries(webhook_id); create index if not exists idx_usage_created on api_usage_logs(created_at desc); create index if not exists idx_events_created on integration_events(created_at desc);

alter table partner_organizations enable row level security; alter table partner_applications enable row level security; alter table api_credentials enable row level security; alter table api_endpoints enable row level security; alter table webhook_configs enable row level security; alter table webhook_deliveries enable row level security; alter table api_usage_logs enable row level security; alter table partner_permissions enable row level security; alter table partner_documents enable row level security; alter table partner_tickets enable row level security; alter table partner_analytics enable row level security; alter table integration_plugins enable row level security; alter table integration_templates enable row level security; alter table integration_sdks enable row level security; alter table oauth_clients enable row level security; alter table integration_events enable row level security; alter table sandbox_environments enable row level security; alter table integration_certifications enable row level security;

create unique index if not exists uq_active_api_credential_environment on api_credentials(application_id, environment, credential_type) where status='active';
