-- Retired demo-data migration.
--
-- This migration is intentionally a no-op. KAYAD production migrations must
-- never seed public marketplace inventory, third-party demo imagery, or fake
-- dealer/vehicle records. Existing environments that previously applied the
-- historical demo seed are unaffected; fresh environments now remain clean.
